Controller JSONRPC implementation generation based on IControllerExt interface added
rdkcentral/Thunder pull request #1256
Opened 2023-02-27 15:13 UTC by HaseenaSainul

2023-02-27 16:04 UTC, sebaszm requested changes

2023-02-27 16:04 UTC, sebaszm commented on Source/WPEFramework/Controller.cpp
> +#endif
Dead code....?

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +    // @json @uncompliant:extended
Do we really want to promote the uncompliant JSON-RPC mode for Controller API?

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +    // @stubgen:omit
Why disable stubs generation?

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +    struct EXTERNAL IControllerExt : public virtual Core::IUnknown {
It seems to me that this could be merged with IController. Using the `@name` and `@alt` tags to provide backwards compatibility at JSON-RPC level, if needed. Since now we have a C++ interface dedicated to JSON-RPC only. Unless we really don't want to expose the other methods via COM-RPC>

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +    };
Some properties got lost in translatation.. Were prefix, latitude, longitude idle time removed on purpose?

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +        virtual uint32_t Harakiri() = 0;
example have a Reboot() c++ method but use `@alt harakiri` to enable an alternative deprecated JSON-RPC method

2023-02-27 16:04 UTC, sebaszm commented on Source/plugins/IController.h
> +        virtual uint32_t Configuration(const string& callsign /* @index */, const string& configuration /* @opaque */) = 0;
All documentation is lost :(

2023-02-28 04:08 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +    // @stubgen:omit
Since this is used for only JSONRPC interface

2023-02-28 04:08 UTC, HaseenaSainul commented on Source/WPEFramework/Controller.cpp
> +#endif
sorry, will remove

2023-02-28 04:09 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +    // @json @uncompliant:extended
it is added to get the exact format for configuration setting case

2023-02-28 04:10 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +    struct EXTERNAL IControllerExt : public virtual Core::IUnknown {
@pwielders, already suggested to split the interfaces logically. So looking to that

2023-02-28 04:10 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +    };
I have referred : https://github.com/rdkcentral/Thunder/blob/master/Source/WPEFramework/ControllerJsonRpc.cpp#L61-L81 these items. I could not see it here

2023-02-28 04:11 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +        virtual uint32_t Harakiri() = 0;
let me check

2023-02-28 04:11 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +        virtual uint32_t Configuration(const string& callsign /* @index */, const string& configuration /* @opaque */) = 0;
will add

2023-02-28 08:02 UTC, sebaszm commented on Source/plugins/IController.h
> +    };
Fair enough, I suppose the implementation takes precedence here.

2023-02-28 08:05 UTC, sebaszm commented on Source/plugins/IController.h
> +    // @json @uncompliant:extended
Perhaps it is acceptable to break the backward compatibility for this one call? @pwielders?

2023-02-28 10:50 UTC, HaseenaSainul commented on Source/plugins/IController.h
> +        virtual uint32_t Harakiri() = 0;
added for StoreConfig and Harakiri

2023-02-28 10:52 UTC, pwielders commented on Source/plugins/IController.h
> +    // @json @uncompliant:extended
What is the method, maybe it is better to ask for forgiveness that for permission ;-)

2023-02-28 12:44 UTC, sebaszm commented on Source/plugins/IController.h
> +    // @json @uncompliant:extended
Property for setting `configuration`, being compliant with JSON-RPC it needs a parameter name for the configuration object, however previously it did not.

2023-03-02 13:10 UTC, pwielders approved these changes, later dismissed
Mainly focused on the interfaces, They look very good so no remarks there. @sebaszm I think we should keep the uncompliant mode on Configurations stuff as it is used to intensively already. We need a lot of forgiveness if we would push it :-)

2023-03-02 13:17 UTC, sebaszm approved these changes, later dismissed
Great that only IConfiguration needs to be uncompliant, the other'sare nicely compliant.

2023-03-06 10:48 UTC, pwielders approved these changes

2023-03-06 10:49 UTC, merged