Updating syslog of dynamic COMRPC/configs when disabled
rdkcentral/Thunder pull request #1270
Opened 2023-03-10 11:03 UTC by VeithMetro

It scared both me and Sebastian that something has failed, whereas in reality it is simply disabled (not configured), so let's not scare others trying to build and run Thunder after the upcoming readme update.

2023-03-10 11:09 UTC, sebaszm commented
The only thing that scares me is a fridge without beer.

2023-03-10 11:12 UTC, sebaszm requested changes
If the path is empty the observer can never be valid. You don't need two conditions to come to this conclusion.

2023-03-10 11:37 UTC, sebaszm approved these changes

2023-03-13 16:17 UTC, pwielders approved these changes

2023-03-14 10:20 UTC, merged