[Messaging] Fixing issues with Controls on initialization and shutdown
rdkcentral/Thunder pull request #1390
Opened 2023-08-04 07:30 UTC by VeithMetro

1. Ensuring the proper initialization of statics in each transition unit on Thunder initialization
2. Calling `Destroy()` on each announced `Control` of every message type to ensure a proper destruction of singletons on shutdown

- Macros had to be wrapped in a function to make them compile
- In `~Controls()` destructor there is a temporary copy of the `ControlList` instead of locking, as we are calling `Destroy()`, which then calls `Revoke()`, and this would cause a deadlock

@pwielders @sebaszm - my unique way to add you as reviewers until I have "great power"

2023-08-08 11:46 UTC, sebaszm requested changes
Core::CriticalSection is recursive, so I this shouln't lock up.

2023-08-08 13:19 UTC, sebaszm submitted a review, later dismissed

2023-08-08 13:40 UTC, pwielders requested changes
I think/hope we still can decouple the preprocessor statement definition to the root, the WarningReproting librabry/cmake.

2023-08-08 13:40 UTC, pwielders commented on Source/WPEFramework/CMakeLists.txt
> +    target_compile_definitions(${TARGET} PUBLIC __CORE_WARNING_REPORTING__)
This looks a bit redundant. This flag should come from the WarningReporting CMake file and not from here as they should be completely independent.  
Also if the flag is set, I was expecting this to be the target_link_libraries(${TARGET}
        PRIVATE {NAMESPACE}WarningReporting::{NAMESPACE}WarningReporting)

@bramoosterhuis how can we make sure that the preprocessor statement (target_compile_definitions) is coming from the WarningReporting Cmake here: https://github.com/rdkcentral/Thunder/blob/master/Source/extensions/warningreporting/CMakeLists.txt#L32 ???

2023-08-09 08:20 UTC, VeithMetro commented on Source/WPEFramework/CMakeLists.txt
> +    target_compile_definitions(${TARGET} PUBLIC __CORE_WARNING_REPORTING__)
You're right, this is not even a bit, but completely redundant, since we already have the same target compile definition in the cmake of core. This one can be removed 😄

2023-08-09 08:51 UTC, pwielders approved these changes

2023-08-09 09:20 UTC, VeithMetro commented
@pwielders I had a chat with @sebaszm, and he agrees on these changes (to unify the registration here with the one in ProxyStubs), so I think we can merge it

2023-08-09 09:31 UTC, merged