[docs]: Add 'Time' documentation.
rdkcentral/Thunder pull request #1432
Opened 2023-10-20 08:09 UTC by msieben

METROL-847

2023-10-20 08:31 UTC, woutermeek commented on docs/utils/time.md
> +Core::Time past(/*year*/ 2023, /*month* 10, /*day*/ 13, /*hours*/ 18, /*minutes*/ 02, /*seconds 0 ,/* milliseconds*/ 0, /*local time*/ true);
Missing / in "/*month*"

2023-10-24 13:26 UTC, MFransen69 requested changes

2023-10-24 13:26 UTC, MFransen69 commented on docs/utils/time.md
> +Core::Time past(/*year*/ 2023, /*month* 10, /*day*/ 13, /*hours*/ 18, /*minutes*/ 02, /*seconds 0 ,/* milliseconds*/ 0, /*local time*/ true);
And missing */ in seconds :)

2023-10-24 13:26 UTC, MFransen69 commented on docs/utils/time.md
> +The external representation of time is a string formatted in a predefined pattern unless a single integer valued element is represented. Such patterns are intrinsically applied for the various conver
Perhaps good to explicitly  indicate we have both from and to conversions for these formats

2023-11-03 11:05 UTC, MFransen69 approved these changes

2023-11-22 10:57 UTC, merged