Development/json types
rdkcentral/Thunder pull request #1433
Opened 2023-10-20 09:40 UTC by msieben

2023-10-24 08:02 UTC, pwielders requested changes
Would like to avoid allocation using new. So far it was never needed hence my quesion what are we fixing that requires this ?

2023-10-24 08:02 UTC, pwielders commented on Source/core/JSON.h
> +                                        case 1  : element = new ArrayType<String>;
What issue is resolved by these allocations. Allocations definitely on these low levels of functionality, might cause fragmentation of memory. So far no issues have been reported that require this allocation so would like to understand the need of this construction. What is the use-case that gives erroneous output without this allocation construction?

2023-10-27 12:37 UTC, msieben commented on Source/core/JSON.h
> +                                        case 1  : element = new ArrayType<String>;
As discussed with @MFransen69 the code path is there not to resolve any reported issue although it shows fields in config.json have no corresponding IElement in the contained list. For debugging purposes and to simplify unit testing for now it has been quite helpful. The use of Add(..) prior Deserialize(..) and ignoring unmatched fields is preferred. A proposed (recommended) approach is to remove the code path from a release delivery and save it elsewhere for use with the aforementioned purposes.

2024-06-04 08:46 UTC, msieben commented
Closing the PR but keeping the related branch.

2024-06-04 08:46 UTC, closed without merging