[FIXES] Addressed review comments from pull request and used new Gene…
rdkcentral/Thunder pull request #1471
Opened 2023-12-16 09:30 UTC by pwielders

…rator tool functionality.

2023-12-16 11:30 UTC, MFransen69 requested changes

2023-12-16 11:30 UTC, MFransen69 commented on Source/core/JSONRPC.h
> +                        Code = -33000 - Core::ERROR_INVALID_RANGE;
Perhaps make a const(expr) out of the 33000 with a meaningful name so it is more clear why we use it as a base for the application errors? If you look in the json rpc spec (as I was curious why it was 33000 anyway :) ) it looks like the codes were written with a signed 16 bits code in mind, but if 32 bit can be used indeed then this should be correct as well.

2023-12-17 16:22 UTC, MFransen69 approved these changes

2023-12-18 07:38 UTC, sebaszm approved these changes

2023-12-18 08:06 UTC, merged