[Macos] First set of changes to support macos build
rdkcentral/Thunder pull request #1536
Opened 2024-03-04 06:44 UTC by sramani-metro

These changes may be common to all platforms

2024-03-06 14:15 UTC, pwielders commented on Source/core/NodeId.h
> +            address_family_t familyType() const
To be inline with all the other methods, use Pascalcase, so FamilyType()

2024-03-06 14:21 UTC, pwielders requested changes
Looks good but lets keep public method names PascalCase (FamilyType) otherwise we are sending a mixed signal about our casing.
Did you check (cause the PR is to big to really validate) the NetworkControlPlugin using dhcp if it still works? This plpugin relies heavily on the IPFrame stuff, so if it is tested you still get an IP address on the Pi through dhcp of the NewtorkControl) I think it is safe to merge... (and the PascalCase update offcourse ;-))

2024-03-25 13:51 UTC, sramani-metro commented
One notable side effect of this change in IPFrame.h is that windows build will start failing, because the definitions of struct ip  and other related data structures are unavailable in windows. We have been using the Linux specific structs namely, struct iphdr and have defined the same in [ThunderOnWindows/](https://github.com/WebPlatformForEmbedded/ThunderOnWindows/blob/master/include/net/ipheaders.h). What i have done now is switch to Posix compliant structs that are available in both Macos and Linux (struct ip and others). This allows us to use Posix Compliant structs and in future if Windows decides to add support for net headers, the Posix compliant ones would get more preference than the Linux ones. 

Other than this, i have changed the Pascal case for the method as requested in the comment and have tested this in a RPI to verify DHCP IP.

2024-04-11 14:02 UTC, pwielders approved these changes, later dismissed

2024-05-08 09:49 UTC, pwielders approved these changes

2024-05-08 13:10 UTC, merged