Thunder R4.4 Build Error Fixed when ProcessContainer enabled
rdkcentral/Thunder pull request #1639
Opened 2024-06-12 15:55 UTC by tabbas651

* Fixed Thunder R4.4..1 Compilation error when enabled ProcessContiainer 
* Correct the UnLock spelling
* Correct the messaging  header file
* updated the ProcessContainers::ProcessContainerization into Trace::Information

2024-06-12 17:48 UTC, karuna2git approved these changes

2024-06-12 17:50 UTC, karuna2git approved these changes

2024-06-12 17:50 UTC, karuna2git commented on Source/extensions/processcontainers/implementations/DobbyImplementation/DobbyImplementation.cpp
> +        _adminLock.Unlock();
ProcessContainers were never compiled for opensource community. So this was not noticed. Thanks for pointing it out

2024-06-12 17:50 UTC, karuna2git commented on Source/extensions/processcontainers/implementations/DobbyImplementation/DobbyImplementation.h
> +#include "messaging/messaging.h"
ProcessContainers were never compiled for opensource community. So this was not noticed

2024-06-12 17:50 UTC, karuna2git commented on Source/extensions/processcontainers/implementations/DobbyImplementation/DobbyImplementation.cpp
> +            TRACE(Trace::Information, (_T("path set to %s for name %s"), _path.c_str(), _name.c_str()));
changing everything from `ProcessContainers::ProcessContainerization` to `Trace::Information` is okey for now.

2024-06-13 07:29 UTC, MFransen69 requested changes

2024-06-13 07:29 UTC, MFransen69 commented on Source/extensions/processcontainers/implementations/DobbyImplementation/DobbyImplementation.cpp
> -            TRACE(ProcessContainers::ProcessContainerization, (_T("searching %s container at %s, %s"), id.c_str(), configBundleFile.Name().c_str(), configBundleFile.PathName().c_str()));
Please also see our comments in the PR for master

2024-06-17 06:40 UTC, MFransen69 commented
We agreed this PR to be closed and the fixes to be incorporated into a fix for the remaining process containers issues

2024-06-17 06:40 UTC, closed without merging