Added buildinfo method (build flags) for QA report
rdkcentral/Thunder pull request #1712
Opened 2024-08-02 07:38 UTC by nxtum

2024-08-02 12:55 UTC, pwielders approved these changes, later dismissed

2024-08-05 12:28 UTC, sebaszm requested changes

2024-08-05 12:28 UTC, sebaszm commented on Source/Thunder/Controller.cpp
> +        #ifdef __CORE_EXCEPTION_CATCHING__
You have exception catching twice.

2024-08-05 12:28 UTC, sebaszm commented on Source/Thunder/Controller.cpp
> +        #elif defined(THUNDER_NDEBUG)
Its _THUNDER_NDEBUG with leading underscore.

2024-08-05 12:28 UTC, sebaszm commented on Source/core/CMakeLists.txt
> +            CompileSettings::CompileSettings
Add PRIVATE CompileSettings to Thunder/CMakeLists.txt instead of exporting compilesettings from Core.

2024-08-12 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=1712) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=1712) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: pwielders<br/>:white_check_mark: nxtum<br/>:white_check_mark: sebaszm<br/>:x: Bieganski<br/><hr/>**Bieganski** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=1712) it.</sub>

2024-08-12 14:25 UTC, sebaszm approved these changes

2024-08-12 21:50 UTC, bramoosterhuis approved these changes

2024-08-15 09:03 UTC, pwielders approved these changes

2024-08-15 09:21 UTC, merged