JSON: add error logs for integer overflow case
rdkcentral/Thunder pull request #1713
Opened 2024-08-05 09:16 UTC by HaseenaSainul

2024-08-05 09:48 UTC, VeithMetro submitted a review, later dismissed

2024-08-19 08:34 UTC, pwielders requested changes

2024-08-19 08:34 UTC, pwielders commented on Source/core/JSON.h
> +
I think you could make this much simpler. Remove the whole current calculation and keep the previous than on line 772 change if (previous != current) to if (previous > _value) and I guess you are done?

2024-08-19 13:09 UTC, HaseenaSainul commented on Source/core/JSON.h
> +
updated the logic as we discussed

2024-08-20 13:11 UTC, pwielders approved these changes

2024-08-20 13:11 UTC, merged