Local and off root config for plugins
rdkcentral/Thunder pull request #1716
Opened 2024-08-07 09:08 UTC by nxtum

Plugins with the root() function would not work in a configuration with: (above configuration) root: Local, and (configuration) root: off  as the libraries would not be loaded. By using string iterator, it allows them to work in that config

2024-08-07 09:21 UTC, VeithMetro requested changes
Some minor formatting changes 😀

2024-08-07 09:21 UTC, VeithMetro commented on Source/Thunder/PluginServer.h
> +            {
A few unnecessary spaces here and one line above 😄

2024-08-07 09:21 UTC, VeithMetro commented on Source/Thunder/PluginServer.h
> +                         if (newLib.IsLoaded() == true) {
One more unnecessary space here 😝

2024-08-07 09:21 UTC, VeithMetro commented on Source/plugins/Shell.cpp
> +                while (all_paths->Next(element) == true){
Add a space before curly bracket

2024-08-07 09:21 UTC, VeithMetro commented on Source/Thunder/PluginServer.h
> +                while((all_paths->Next(element) == true) && (progressedState <= 2)){
Add space before a curly bracket

2024-08-09 11:14 UTC, pwielders approved these changes

2024-08-09 11:19 UTC, VeithMetro approved these changes

2024-08-09 11:20 UTC, merged