JSON type added for ThunderId
rdkcentral/Thunder pull request #1736
Opened 2024-09-04 12:05 UTC by HaseenaSainul

2024-09-23 09:23 UTC, sebaszm requested changes

2024-09-23 09:23 UTC, sebaszm commented on Source/Thunder/PluginHost.cpp
> +        printf("  Thread%02d|0x%16" PRIu64 ": %10d", (index), static_cast<uint64_t>(workerId), runs);
This is DWORD on Windows, so no need to go through uint64_t.

2024-09-23 09:23 UTC, sebaszm commented on Source/core/JSON.h
> +            ThreadId(const ThreadId&& move)
moved object must not be const to be moved

2024-09-23 09:23 UTC, sebaszm commented on Source/core/JSON.h
> +                return static_cast<thread_id>(Core::NumberType<uint64_t, false, NumberBase::BASE_HEXADECIMAL>(String::Default().c_str(), static_cast<uint32_t>(String::Default().length())).Value());
Again it doesnt need to be as big as uint64_t

2024-09-23 09:23 UTC, sebaszm commented on Source/core/JSON.h
> +            inline thread_id Value() const
::thread_id

2024-09-23 09:23 UTC, sebaszm commented on Source/core/JSON.h
> +        typedef ThreadId Pointer;
Perhaps it's better to remove the Pointer typedef all along? As it's either gonna be InstanceId or ThreadId and update the code that's using it accordingly.

2024-09-23 09:23 UTC, sebaszm commented on Source/core/Portability.h
> +typedef pthread_t thread_id;
Why not Core::thread_id? Consistenly with Core::instance_id?

2024-09-23 09:23 UTC, sebaszm commented on Source/plugins/IController.h
> +                ::thread_id Id /* @brief Thread ID */;
This means that IMetadata can't go over COM-RPC.

2024-09-23 09:23 UTC, sebaszm commented on Source/plugins/Metadata.cpp
> +        Id = (::thread_id)info.WorkerId;
There seems to be a lot of C-style casting to ::thread_id throughout code...

2024-09-23 09:23 UTC, sebaszm commented on Source/core/Thread.cpp
>  PUSH_WARNING(DISABLE_WARNING_CONVERSION_TO_GREATERSIZE)
thread_id is DWORD and GetCurrentThreadId() return DWORD, why would there be a warning?

2024-09-30 12:31 UTC, HaseenaSainul commented
There is no permission to update the branch in rdkcentral, so new PR created from fork: https://github.com/rdkcentral/Thunder/pull/1766.
Hence closing this PR.

2024-09-30 12:31 UTC, closed without merging