Allow jsonrpc for plugin suspend/resume
rdkcentral/Thunder pull request #1799
Opened 2024-11-27 10:29 UTC by nxtum

2024-11-27 14:22 UTC, pwielders commented on Source/Thunder/Controller.cpp
> +                    NotifySuspendResumeStateChange(callsign, Exchange::Controller::ILifeTime::state::RESUMED);
I think this is too early, we can only do so if the state is indeed changed. You know that if you would subscribe to the IStateControl::INotification interface. What if the Suspend or Resume fails ?
Lets have a broader discussion on this if we want this as this has some severe impact..

2024-11-27 14:23 UTC, pwielders commented on Source/Thunder/Controller.cpp
> +                    NotifySuspendResumeStateChange(callsign, Exchange::Controller::ILifeTime::state::SUSPENDED);
I think this is too early, we can only do so if the state is indeed changed. You know that if you would subscribe to the IStateControl::INotification interface. What if the Suspend or Resume fails ?
Lets have a broader discussion on this if we want this as this has some severe impact..

2024-12-06 12:33 UTC, pwielders requested changes
As discussed in the call. The issue is that we need to "wait" for the statechange to actually occure (moving to SUSPENDED/RESUMED) and not already issue this at the moment it is being requested as at that time the plugin did not yet "reach" that state.
To accomodate that we discussed putting the subscribng on the IStateControl::INotification in the PluginHost::Server::Service::AcquireInterface(https://github.com/rdkcentral/Thunder/blob/master/Source/Thunder/PluginServer.h#L1479) and the releasing of this interface on the PluginHost::Server::Service::ReleaseInterface(https://github.com/rdkcentral/Thunder/blob/master/Source/Thunder/PluginServer.h#L1563). Than hooping through the _administrator in this class (https://github.com/rdkcentral/Thunder/blob/master/Source/Thunder/PluginServer.h#L1649) you can get to the Controller to send the statechanges for each plugin to subscribers of the controller.

Note that you probably do not need to create a SinkType<> for the Service to receive the notifications as you can just "extend" the Composit (https://github.com/rdkcentral/Thunder/blob/master/Source/Thunder/PluginServer.h#L387) already a member here as _composit (https://github.com/rdkcentral/Thunder/blob/master/Source/Thunder/PluginServer.h#L1650) with the IStateControl::INotification interface to get the required changes!

2025-02-07 11:51 UTC, sebaszm approved these changes, later dismissed
Looks good! 
I do not myself have a better name for StateControlStateChange.

2025-02-07 12:41 UTC, pwielders commented on Source/Thunder/PluginServer.cpp
> +            case IStateControl::state::EXITED:
Just checked the EXITED state, since I did not understaood what it meant, and it looks like it is not used at all. Could we try to remove it (from interface and here) and see if it still all compiles ?

2025-02-07 12:44 UTC, sebaszm commented on Source/Thunder/PluginServer.cpp
> +            case IStateControl::state::EXITED:
It is used, if the plugin/application itself requests to quit.

2025-02-10 14:52 UTC, sebaszm approved these changes

2025-02-10 17:01 UTC, pwielders approved these changes

2025-02-10 17:02 UTC, merged