Fix resuming of restarted apps (after crash)
rdkcentral/Thunder pull request #257
Opened 2020-09-04 19:56 UTC by emutavchi

The ResidentApp (UX) callsign needs to be resumed after restarded by the Monitor

2020-09-05 08:25 UTC, pwielders requested changes
This is an abuse of the functionality :-) It is not intended to continuously resume a plugin that was configured to start at startup. If you want to have that behavior, use the flag on the plugin called: 
https://github.com/rdkcentral/Thunder/blob/master/Source/plugins/Configuration.h#L53
This flag is intended to change the default start of the plugin to "always" start resumed. This functionality is intended to do it only once at initial startup. So please use the functionality indicated above .

2020-09-06 01:34 UTC, emutavchi commented
Hi @pwielders, thanks for review. I updated the pull request to make "resumed" configurable through the project config

2020-09-07 14:47 UTC, pwielders commented
I think that is fine but my cmake knowledge is limited, leave it up to bram to reviw.

2020-09-07 15:29 UTC, pwielders approved these changes

2020-09-07 15:51 UTC, bramoosterhuis approved these changes

2020-09-07 16:35 UTC, merged