Avoid of earlier closelog to prevent of related crashes
rdkcentral/Thunder pull request #284
Opened 2020-09-21 08:51 UTC by Gavriliuk

2020-09-21 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) before we can accept your contribution.<br/><hr/>**Alexandr Gavriliuc** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=284) it.</sub>

2020-09-21 09:25 UTC, pwielders requested changes
@Gavriliuk can you sign the CLA (some kind of form that you are aware this is open source) Only if you signed it I can merge your change, but also could you just move The closelog() lines till after the Core::Singleton::Dispose(). 
I do think it is important to clean up what you created (or close what you opened) agree, I think we are doing that here to early.

2020-09-22 05:03 UTC, goruklu submitted a review, later dismissed

2020-09-22 12:41 UTC, Gavriliuk commented
@pwielders I agree to sign the CLA but don't see a link for it - could you please provide it here?

Regarding **closelog()**

We observe a lot of crashes related to logging attempts from any threads after the process is being terminated
I'm not sure that moving the call of closelog() one line below fixes the issue

From the other hand, it seems we don't need to call closelog() because it's use is optional
https://linux.die.net/man/3/closelog

**"Syslog connections are automatically closed on exec or exit."**
https://www.gnu.org/software/libc/manual/html_node/closelog.html

Currently we call **openlog()** the following way:

> openlog(argv[0], LOG_PID, LOG_USER);

It seems we'd better use the following form:

> openlog(NULL, LOG_PID, LOG_USER);

This means use argv[0] internally and don't reserve a pointer for **ident**

2020-09-25 13:23 UTC, pwielders requested changes

2020-12-16 09:04 UTC, MFransen69 commented
As there was no activity for some time I close the PR. Of course please reopen if it is still desired to respond to the requested changes.

2020-12-16 09:04 UTC, closed without merging