Refpltv 728 controller delete not deleting files
rdkcentral/Thunder pull request #438
Opened 2021-01-21 07:32 UTC by swati-varahagiri

RDK Services: "Controller.1.delete" is not deleting the contents of the directory on Reference platform.

2021-01-21 07:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=438) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=438) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: vijs<br/>:white_check_mark: HaseenaSainul<br/>:white_check_mark: woutermeek<br/>:white_check_mark: pwielders<br/>:white_check_mark: neeraj-deshpande<br/>:x: swati-varahagiri<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=438) it.</sub>

2021-01-21 07:59 UTC, HaseenaSainul commented
@swati-varahagiri, could you please resolve conflicts. Seems you are pushing the existing changes itself.

2021-01-21 10:05 UTC, pwielders requested changes
I think this has been superseded by the othere two commits where I think you just need to cherry pick the fixes @HaseenaSainul and @brainstem123 already did, so please just submitt hases to be cherry picked into the REL1.5 branch to keep the github administration clean and accurate.

2021-01-22 12:20 UTC, swati-varahagiri commented
Raising a new PR as suggested.

2021-01-22 12:20 UTC, closed without merging