REFPLTV-735: RDK Services: Controller.1.startdiscovery and Controller…
rdkcentral/Thunder pull request #441
Opened 2021-01-21 09:39 UTC by swati-varahagiri

….1.discoveryresults returning Empty reply from server error

Reason for change: Crash observed when Controller.1.startdiscovery and Controller.1.discoveryresults are run.
Test Procedure: Execute Controller.1.startdiscovery and Controller.1.discoveryresults curl command.

2021-01-21 09:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=441) it.</sub>

2021-01-21 09:51 UTC, pwielders commented
I think tis is causing havoc in the tracking and tracing of the GitHub system, please use the commits already submitted to resolve this and do not create new pull requests this issue is already resolved by commit: 9a4a4ece02d0bba8f89db03f5aa85aba36ddc5ad just cherry pick it on the Rel1.5 branch if required.

2021-01-21 09:55 UTC, pwielders requested changes
Please use the cherry-pick functionality from guiithub and create a pull request with the two indicated hashes.

2021-01-22 10:11 UTC, swati-varahagiri commented
Raising a new PR as suggested.

2021-01-22 10:11 UTC, closed without merging