[NEW FUNCTIONALITY] Add a suspend and resume to the controller.
rdkcentral/Thunder pull request #453
Opened 2021-02-03 10:43 UTC by pwielders

2021-02-03 10:53 UTC, MFransen69 requested changes

2021-02-03 10:53 UTC, MFransen69 commented on Source/WPEFramework/PluginServer.cpp
> +                    stateControl->Release();
Think this release needs outside the if condition

2021-02-03 10:53 UTC, MFransen69 commented on Source/WPEFramework/PluginServer.cpp
> +                        stateControl->Release();
Same as above

2021-02-03 10:53 UTC, MFransen69 commented on Source/WPEFramework/json/Controller.json
> +    "Controller.1.resume": {
Think we should also regenerate the documentation from this (but that is not super urgent indeed)

2021-02-03 10:55 UTC, pwielders commented on Source/WPEFramework/PluginServer.cpp
> +                        stateControl->Release();
good point let me update

2021-02-03 11:01 UTC, sebaszm commented on Source/WPEFramework/PluginServer.cpp
> +                // We have a StateControl interface, so at least start suspending, if not already suspended :-)
same here

2021-02-03 11:05 UTC, pwielders commented on Source/WPEFramework/PluginServer.cpp
> +            // See if we need can and should SUSPEND.
hmmm, seems someone copied :-)

2021-02-03 11:20 UTC, sebaszm submitted a review, later dismissed

2021-02-03 11:26 UTC, MFransen69 submitted a review, later dismissed

2021-02-17 19:18 UTC, pwielders commented
Although no longer strictly needed, as it is build, maybe good to add..

2021-02-17 19:24 UTC, MFransen69 approved these changes

2021-02-22 08:48 UTC, sebaszm approved these changes

2021-02-22 11:15 UTC, merged