[SOCKETPORT] Extract from UDP/RAW messages on which interface they wh…
rdkcentral/Thunder pull request #485
Opened 2021-02-25 14:52 UTC by pwielders

…ere received.

To make the locator specific to the IP address on the interface it was received, extract the interface id, with the remote address, on which it was received. This way the Locator can be made to use the IPv4/IPv6 address for that interface to reach it back on.

2021-02-25 15:37 UTC, MFransen69 submitted a review, later dismissed

2021-03-06 00:46 UTC, sebaszm requested changes

2021-03-06 00:46 UTC, sebaszm commented on Source/core/SocketPort.h
> +        uint32_t m_Interface;
m_Interface is missing initialization (~0 ?)

2021-03-08 10:14 UTC, sebaszm approved these changes
Works great. Good to merge

2021-03-08 11:58 UTC, merged