Set all file descriptors as close on exit to prevent them from being …
rdkcentral/Thunder pull request #510
Opened 2021-03-17 15:42 UTC by gladish

…inherited by WPEProcess

2021-03-18 08:09 UTC, pwielders commented on Source/core/DoorBell.cpp
> +        #ifdef __LINUX__
The SOCK_CLOEXEC is also available on windows so no need to use the preprocessor to diffrentiate.

2021-03-18 08:12 UTC, pwielders commented on Source/core/SocketPort.cpp
> +        #ifdef __LINUX__
Windows does support SOCK_CLOEXEC as well so lets not diffrentiate her

2021-03-18 08:17 UTC, pwielders commented on Source/core/SocketPort.cpp
> +        #else
Could not find the accept4 in the windows documentation that quickly, but suggest we remove the preprocessor stuff anyway. I will test it on windows and if I run into an issue I will just create a local accept4 method in this compilation unit that will push the SOCK_CLOEXEC option onto the socket. I am afraid if I am not running into a compilation issue, we forget about this change.

2021-03-18 08:18 UTC, pwielders requested changes
Looks good, just would like to drop the __LINUX_ guards you added. If it hurst in windows (and I think only the accept4 will) we will fix it so that also on windows, connecting sockets get the SOCK_CLOEXEC flag.

2021-03-19 07:59 UTC, pwielders approved these changes
Looks good to me. Waiting for @HaseenaSainul to make sure that we do not introduce any regression if she reports no regression good to merge!

2021-03-19 11:29 UTC, HaseenaSainul approved these changes
LGTM

2021-03-19 12:27 UTC, merged