Implement new api for write without response
rdkcentral/Thunder pull request #691
Opened 2021-08-18 09:26 UTC by Preejar

Adding new api named WriteCommand to write value of
 attribute. No error response or write response sent
 in response to this command.Added opcode for this as 0x52.
 Also introduced new execute() api to send the data without
 response.

2021-08-18 09:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=691) before we can accept your contribution.<br/><hr/>**Preeja Raveendran** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=691) it.</sub>

2021-08-26 17:18 UTC, sebaszm requested changes

2021-10-06 09:48 UTC, Preejar commented on Source/bluetooth/GATTSocket.h
> +                _error = ~0;
@sebaszm ,

you mean here put _error  =  Core::ERROR_NONE instead of ~0?

2021-10-06 09:48 UTC, Preejar commented on Source/bluetooth/GATTSocket.h
> +            Send(CommunicationTimeOut, cmd, &_sink, NULL);
Ok.I will test and update this

2021-10-06 10:24 UTC, sebaszm commented on Source/bluetooth/GATTSocket.h
> +                _error = ~0;
Correct.

2021-10-12 09:04 UTC, Preejar commented
Raised v2 version for this PR by fixing review comments

https://github.com/rdkcentral/Thunder/pull/768/commits/2423fdd00b57b3fa50f651a221808945c1223fb7

2021-10-12 09:04 UTC, closed without merging