[CRYPTO] Adds NetflixVaultGenerator
rdkcentral/Thunder pull request #73
Opened 2020-04-29 12:56 UTC by svdmaar

Adds Netflix Vault Generator.

2020-05-01 14:42 UTC, sebaszm requested changes

2020-05-01 14:42 UTC, sebaszm commented on Tests/cryptography/NetflixVaultGenerator/main.cpp
> +const uint32_t g_esnSize = 42;
Why is the ESN size fixed? I don't think it's always 42...? Did a quick search on the net and found different sizes of sample ESNs. The TA even has dedicated API to retrieve the ESN size, hence my doubts.

2020-05-01 14:42 UTC, sebaszm commented on Tests/cryptography/NetflixVaultGenerator/main.cpp
> +    }
OpenSSL has cryptography-strong random number generator functions RAND_***, why not use them instead?

2020-05-01 14:42 UTC, sebaszm commented on Tests/cryptography/NetflixVaultGenerator/main.cpp
> +    cout << "SUCCESS: Written netflix fault to " << argv[2] << endl;
Yeah, it's their fault! :)

2020-05-15 06:30 UTC, svdmaar commented
@sebaszm , thanks for you review feedback, I agree with all the points raised and amended a commit. Please have another look at this PR. Thanks

2020-05-15 07:45 UTC, sebaszm approved these changes
LGTM!

2020-05-15 12:20 UTC, merged