[Metrol305] Changes for notifying syslog logging.
rdkcentral/Thunder pull request #732
Opened 2021-09-16 08:14 UTC by Karthick-Somasundaresan

When WPEFramework does a Syslog, it will notify the
message to the registered monitoring clients

2021-09-21 10:58 UTC, sramani-metro requested changes

2021-09-21 10:58 UTC, sramani-metro commented on Source/tracing/SyslogMonitor.h
> +    class EXTERNAL SyslogMonitorClient
If this is intended to be an interface, then better to follow the style of declaring it as a struct with a virtual destructor with naming conventions like ISyslogClient or so.

2021-09-21 10:58 UTC, sramani-metro commented on Source/tracing/SyslogMonitor.h
> +            static SyslogMonitor& Instance()
If this is supposed to be a singleton in the Thunder process, why not use the SingletonType Template to make use of the lifecycle management the framework offers?

2021-09-24 10:04 UTC, sramani-metro approved these changes, later dismissed

2021-09-30 08:24 UTC, MFransen69 requested changes

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/ISyslogMonitorClient.h
> +    class EXTERNAL ISyslogMonitorClient
`for interfaces we usually use struct so we do not have to specify public, improves the readability a bit

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/ISyslogMonitorClient.h
> +            virtual ~ISyslogMonitorClient(){}
In interfaces we usually prefer = default instead of an empty implementation. In some cases that might be more performant.

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/SyslogMonitor.h
> +                _monitorClients.push_back(client);
For safety I would at least add an assert to check if the client is already registered and if they are not trying to register a nullptr

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/SyslogMonitor.h
> +                _monitorClients.push_back(client);
I guess some locking would also not hurt. What would happen if a client would just be (un)registered while at the same time another thread would log something to syslog?

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/SyslogMonitor.h
> +                return;
Might not be explicitly in our coding guideline but we never use returns without return value. So to keep our code base consistent could you please remove them?

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/SyslogMonitor.h
> +            {
would also add an assert for client being nullptr

2021-09-30 08:24 UTC, MFransen69 commented on Source/tracing/ISyslogMonitorClient.h
> +            virtual void NotifyLog(const std::string& logmessage) = 0;
Why a std::string? We use string to be able to move to multi byte codewords in tghe future (e.g. UTF-16).

2022-01-19 14:45 UTC, MFransen69 commented
As discussed: we are redesigning the way reporting is done in general that will have a big influence on this PR or even  makes it not needed anymore. Let's see when the new reporting engine is in place

2022-01-19 14:45 UTC, closed without merging