Bluetooth: add SDP and AVDTP profiles
rdkcentral/Thunder pull request #812
Opened 2021-10-29 10:00 UTC by sebaszm

- Introduce SDP Profile (client+server) and AVDTP profile (client), RTP packetizing
- Small fixes around BR/EDR connecting and PIN handling
- Rename Profile to GATTProfile

2021-11-01 11:42 UTC, pwielders reviewed
Suggest building with Hidden symbols :-) Missing the EXTERNAL keyword on classes. This is what is applicable in the Yocto build maybe we should enable it by default as wel.. (https://github.com/rdkcentral/Thunder/blob/master/Source/CMakeLists.txt#L90 )

2021-11-04 22:59 UTC, pwielders approved these changes

2021-11-04 23:01 UTC, pwielders commented on Source/CMakeLists.txt
> +set (HIDE_NON_EXTERNAL_SYMBOLS true)
Think we need to remove this setting, but maybe good to, by default, already enable this in our builds so it aligns better with the latest Yocto builds and keeps the binaries smaller.

2021-11-04 23:02 UTC, pwielders requested changes
Minor, you left the hidden flag on but might be good to change the default to "on" and only with an override you can make everything visible again.

2021-11-05 07:48 UTC, sebaszm commented
Drat, I didn't mean to commit that change, that was only for test... But the test proved useful, there was more that needed EXTERNAL than I originally anticipated. Let me remove it, it shouldn't be done this anyway.

2021-11-05 08:13 UTC, pwielders approved these changes
Oke lets bring it in :-)

2021-11-05 08:13 UTC, merged