[WINDOWS] Get tracing in the new messaging setup working under window…
rdkcentral/Thunder pull request #950
Opened 2022-05-04 08:05 UTC by pwielders

…s again.

Windows does not support Domain sockets so for windows it should be possible to
define a port number on the loopback interface (127.0.0.1) as a domain socket alternative.
This pull request adds the possibility (if the port is not 0) to use a loopback IP socket
for communication in stead of a domain socket. This allwos the messaging concept to also
work on a windows platform.

2022-05-05 06:16 UTC, lukiwa commented on Source/core/MessageDispatcher.h
>           * @param baseDirectory where to place all the necessary files. This directory should exist before creating this class.
Add socket port to docs

2022-05-05 06:16 UTC, lukiwa commented on Source/core/MessageDispatcher.h
>           * @param baseDirectory where to place all the necessary files. This directory should exist before creating this class.
Add socket port to docs

2022-05-05 06:17 UTC, lukiwa commented on Source/core/MessageDispatcher.h
> +        static Filenames PrepareFilenames(const string& baseDirectory, const string& identifier, const uint32_t instanceId, const uint16_t socketPort)
Also here, add socket port to the Doxygen docs.

2022-05-05 06:17 UTC, lukiwa commented on Source/core/MessageDispatcher.h
> +        static Filenames PrepareFilenames(const string& baseDirectory, const string& identifier, const uint32_t instanceId, const uint16_t socketPort)
Also here, add socket port to the Doxygen docs.

2022-05-05 06:18 UTC, lukiwa commented on Source/core/MessageUnit.cpp
> +        uint32_t MessageUnit::Open(const string& pathName, const uint16_t socketPort)
Also here, add to docs :)

2022-05-05 06:18 UTC, lukiwa commented on Source/core/MessageUnit.cpp
> +        uint32_t MessageUnit::Open(const string& pathName, const uint16_t socketPort)
Also here, add to docs :)

2022-05-05 06:18 UTC, lukiwa commented on Source/messaging/MessageClient.cpp
> +    MessageClient::MessageClient(const string& identifer, const string& basePath, const uint16_t socketPort)
And here, docs

2022-05-05 06:18 UTC, lukiwa commented on Source/messaging/MessageClient.cpp
> +    MessageClient::MessageClient(const string& identifer, const string& basePath, const uint16_t socketPort)
And here, docs

2022-05-05 06:22 UTC, lukiwa requested changes
It is OK, but since "socket port messaging" will not be used on Linux, maybe it would be good to somehow hide constructors and methods behind defines? Or create separate constructors allowing construction of the "messaging backend" in two distinct ways? Let me know what do you think

2022-05-06 08:45 UTC, pwielders commented
@lukiwa it could be used on linux as well however it is not recommended as the domain sockets are faster. So hiding it behind a Preprocessor might reduce code size but also hides a potential feature.
I am a bit in the middle. See advantages for left and see advantages for right. So your opinion is decisive. Where do you want to go?
And agree will update the documentation of Doxygen :-)

2022-05-06 11:42 UTC, lukiwa commented
Agree, maybe we can use this feature for something in the future. Personally, I would go for two constructors (or specific methods) - one for constructing domain socket (with argument basePath) and the second one with argument socketPort. 
Optionally, if the code size is an issue, maybe just set the default value for socketPort arguments as 0?

2022-05-06 12:33 UTC, lukiwa approved these changes

2022-05-06 14:14 UTC, merged