RDKTV-17127 : WPEFramework crash at std::terminate
rdkcentral/Thunder pull request #981
Opened 2022-06-09 07:41 UTC by nsahu910

Reason for change: Setting unused pointer to null
Test Procedure: mentioned in the ticket.
Risks: None
Signed-off-by: Neeraj Sahu Neeraj_Sahu@comcast.com

2022-06-09 09:44 UTC, pwielders requested changes
If this happens it means that there is something more serious going on. 
Scary part is that it means that the destruction can occure from two sides (double destruction) if the _destructor on line 185 occurs just before the pointer is pushed to the stack (and not null), the Thread will destruct in CloseDown *AND* it gets destrcuted on line 178.
so to fix this properly, you should lock the passing on of the _destrcutor member variable and clear it within the locl on line 185

2022-06-09 10:34 UTC, nsahu910 commented
thanks @pwielders ,
i have added lock before closeDown, please check.

2022-06-09 12:16 UTC, pwielders commented
Is there a reproduction scenario for the issue that this pull request would fix ?

2022-06-10 08:33 UTC, pwielders commented
@nsahu910 does this fix the crash ? Is it 100% reproducible ?

This looks like colleteral damage from a crashing YouTube application. I can not imagine, but please prove me wrong, that this patch fixes the YouTube crash.

2022-06-13 11:11 UTC, nsahu910 commented
changes not required.

2022-06-13 11:11 UTC, closed without merging