RDK-28700:Thunder iCryptography Port to RDK Security API
rdkcentral/Thunder pull request #99
Opened 2020-06-01 11:57 UTC by yashaswini-rk

Reason for change:SecApi Backend for Icrypto.Compiled Code.

2020-06-01 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=99) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=99) before we can accept your contribution.<br/><hr/>**yramak601** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=99) it.</sub>

2020-06-03 13:04 UTC, sebaszm requested changes
Please make sure the code compiles, does not crash or leak memory. Please use coherent indenting and white-spacing.

2020-06-04 07:12 UTC, sebaszm requested changes
Please make sure the code compiles, does not crash or leak memory. Please use coherent indenting and white-spacing.

2020-06-04 07:12 UTC, sebaszm commented on Source/cryptography/implementation/SecApi/Cipher.cpp
> +            uint16_t length = _vault->Export(_keyId, _keyLength, keyBuf, true);
This surely can't compile, the prototype is different.

2020-12-16 09:05 UTC, MFransen69 commented
As there was no activity for some time I close the PR. Of course please reopen if it is still desired to respond to the requested changes.

2020-12-16 09:05 UTC, closed without merging